[project]
authors = ["Yicheng Huang <huanyic1@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "resprop"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.2"

[tasks]

[dependencies]
python = ">=3.9,<3.11.0a0"
pytorch-gpu = "*"
transformers = ">=4.46.0"
datasets = ">=3.1.0,<4"
accelerate = ">0.26.0"
scikit-learn = ">=1.5.2,<2"
matplotlib = ">=3.9.2,<4"

[pypi-dependencies]
evaluate = ">=0.4.3"

[build-dependencies]
jupyter = ">=1.1.1,<2"
pixi-pycharm = ">=0.0.8,<0.0.9"
