[project]
authors = ["Yicheng Huang <huanyic1@gmail.com>"]
channels = ["pytorch", "nvidia", "conda-forge"]   # order matters
description = "C-Sharp"
name = "C-Sharp"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "11.8"   # matches your machine (__cuda=11.8)

[dependencies]
python = "3.9.*"

# GPU PyTorch
pytorch = "2.4.*"
pytorch-cuda = "11.8"     # do NOT add cudatoolkit when using this

# Hugging Face (conda-forge-friendly versions)
transformers = "<=4.44"
accelerate = "==0.28.0"
datasets = "<=2.21"
evaluate = "*"            # take from conda(-forge), not PyPI

# Others
scikit-learn = ">=1.5.2,<2"
matplotlib = "3.8.*"

[build-dependencies]
jupyter = ">=1.1,<2"
pixi-pycharm = ">=0.0.8,<0.0.9"